esphome:
  name: garden-1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Garden Fallback"
    password: "fyGV6Y7bRk"

globals:
  - id: interval_on_sec
    type: int
    restore_value: true
    initial_value: 30
  - id: interval_off_sec
    type: int
    restore_value: false
    initial_value: 6000

captive_portal:
logger:
api:
  # services:
  #   - name: "Run Zone 1"
  #     service: run_zone_1
  #     then:
  #       - script.execute: irrigation_cycle
  #   - name: "Update on delay"
  #     service: update_on_delay
  #     variables:
  #       new_interval: int
  #     then:
  #       - globals.set:
  #           id: interval_on_sec
  #           value: !lambda "return new_interval;"


ota:


binary_sensor:
  - platform: template
    name: "Irrigation Zone 1 State"
    id: irrigation_zone_1_state

switch:
  - platform: template
    name: Irrigation Zone 1
    id: irrigation_zone_1
    lambda: return id(relay1).state;
    optimistic: true
    turn_on_action:
      - switch.turn_on: relay1
      - binary_sensor.template.publish:
          id: irrigation_zone_1_state
          state: ON
    turn_off_action:
      - switch.turn_off: relay1
      - binarry_sensor.template.publish:
          id: irrigation_zone_1_state
          state: OFF
  - platform: gpio
    pin: D4
    id: relay1


script:
  - id: irrigation_cycle
    mode: single
    then:
      - switch.turn_on: irrigation_zone_1
      - delay:
          seconds: id(interval_on_sec)
      - switch.turn_off: irrigation_zone_1

interval:
  - id: irrigation_zone_1_interval
    interval:
      seconds: id(interval_off_sec)
    then:
      - script.execute: irrigation_cycle


time:
  - platform: sntp
    id: home_time
    timezone: America/Detroit
    servers:
      - "10.4.20.115"
      - "0.us.pool.ntp.org"
      - "1.us.pool.ntp.org"
