esphome:
  name: lilygo-test
  platform: ESP32
  board: esp32dev

# esp32:
#   board: esp32dev
#   framework:
#     type: arduino

logger:

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://ashald/esphome@lilygo-t5-47
    components:
      - lilygo_t5_47

time:
  - platform: homeassistant
    id: ntp

font:
  - id: large
    file: "pixelmix.ttf"
    size: 100

display:
  - platform: lilygo_t5_47
    id: eink
    update_interval: 10s
    full_update_every: 6
    lambda: |-
       it.printf(20, 20, id(large), id(ntp).now().strftime("%Y-%m-%dT%H:%M:%S").c_str());
