esphome:
  name: office-1
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Office Fallback"
    password: "huo1rMZ7ugdp"

# mqqt:
#   broker: 10.4.20.x
#   username: office-1
#   password: !secret mqqt_password

captive_portal:

logger:

api:

ota:

i2c:
  - id: bus_a
    sda: 12
    scl: 13
  - id: bus_b
    sda: 27
    scl: 14

font:
  - id: digit_font
    file: "pixelmix.ttf"
    size: 10
  - id: font3
    file: "pixelmix.ttf"
    size: 24
  - id: remixicon
    file: remixicon.ttf
    size: 10
    glyphs:
      - 0xf2bf
      - 0xf2c1

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.rectangle(1, 1, 126, 62);
      it.strftime(5, 10, id(font3), TextAlign::BASELINE_LEFT, "%H:%M", id(sntp_time).now());

      // Print wifi status
      it.printf(125, 3, id(remixicon), TextAlign::TOP_RIGHT, "%s", wifi.connected ? "0xf2bf" : "0xf2c1");

      // Print inside temperature (from homeassistant sensor)
      if (id(bme280_temp).has_state()) {
        it.printf(125, 10, id(digit_font), TextAlign::TOP_RIGHT , "%.1f°", id(bme280_temp).state);
      }

# display:
#   - platform: max7219digit
#     cs_pin: D3
#     num_chips: 4
#     intensity: 7
#     spi_id: display_spi
#     lambda: |-
#       it.write(d)
#       it.strftime(0, 0, id(digit_font), "%H:%M", id(sntp_time).now());

time:
  - platform: sntp
    id: sntp_time


sensor:
  - platform: bme280
    temperature:
      id: bme280_temp
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      id: bme280_pressure
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
      id: bme280_humidity
    i2c_id: bus_b
    address: 0x76
    update_interval: 60s

# sensor:
#   - platform: dht
#     pin: D13
#     temperature:
#       id: office_temperature
#       name: "Office Temperature"
#       unit_of_measurement: "°F"
#       device_class: "temperature"
#     humidity:
#       id: office_humidity
#       name: "Office Humidity"
#       device_class: "humidity"

# sensor:
#   - platform: mqqt_subscribe
#     name: "Display queue"
#     id: display_queue
#     topic: office/display
