# 4 relay board
---
esphome:
  name: relay-board
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "relay-board"
    password: "NoVNR2vHou"

captive_portal:
logger:
api:
ota:


time:
  - platform: sntp
    id: sntp_time
    timezone: America/Detroit
    on_time:
      - seconds: 0
        minutes: 30
        hours: 7
        then:
          - light.turn_on: grow_light_1
      - seconds: 0
        minutes: 30
        hours: 1
        then:
          - light.turn_off: grow_light_1
output:
  - id: out_relay_1
    platform: gpio
    pin: GPIO16
  - id: out_relay_2
    platform: gpio
    pin: GPIO14
  - id: out_relay_3
    platform: gpio
    pin: GPIO12
  - id: out_relay_4
    platform: gpio
    pin: GPIO13

# Use the blue LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO5
    inverted: True

switch:
  - id: relay_1
    platform: output
    name: "Relay 1"
    output: out_relay_1
  - id: relay_2
    platform: output
    name: "Relay 2"
    output: out_relay_2
  - id: relay_3
    platform: output
    name: "Relay 3"
    output: out_relay_3
  - id: relay_4
    platform: output
    name: "Relay 4"
    output: out_relay_4

light:
  - platform: binary
    id: grow_light_1
    name: "Grow Light 1"
    output: out_relay_1
