# 4 relay board
---
substitutions:
  devicename: relay-board
  friendly_name: "Relay Board"

esphome:
  name: relay-board
  platform: ESP8266
  board: esp12e
  on_boot:
    - ds1307.read_time:

globals:
  - id: on_hour
    type: int
    restore_value: true
    initial_value: "7"
  - id: off_hour
    type: int
    restore_value: true
    initial_value: "19"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "relay-board"
    password: "NoVNR2vHou"

captive_portal:
logger:
api:
ota:

# script:
#   - id: set_light_state
#     then:
#       - if:
#           condition:
#             lambda: 'id(time).hour >= 7 && id(time).hour < 19'

i2c:
  - sda: 5
    scl: 4
    scan: true
sensor:
  - platform: uptime
    name: $friendly_name Uptime
    update_interval: 60s
  - platform: wifi_signal
    name: "$friendly_name WiFi Signal"
    update_interval: 15s

text_sensor:
  - platform: version
    name: $friendly_name Version

time:
  - platform: ds1307
    update_interval: never
    address: 0x68
  - platform: sntp
    id: sntp_time
    timezone: America/Detroit
    on_time_sync:
      - ds1307.write_time:
    on_time:
      - seconds: 0
        minutes: 30
        hours: 7
        then:
          - light.turn_on: grow_light_1
      - seconds: 0
        minutes: 30
        hours: 1
        then:
          - light.turn_off: grow_light_1

output:
  - id: out_relay_1
    platform: gpio
    pin: GPIO16
  - id: out_relay_2
    platform: gpio
    pin: GPIO14
  - id: out_relay_3
    platform: gpio
    pin: GPIO12
  - id: out_relay_4
    platform: gpio
    pin: GPIO13

# Use the blue LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO5
    inverted: True

switch:
  - id: relay_1
    platform: output
    name: "Relay 1"
    output: out_relay_1
  - id: relay_2
    platform: output
    name: "Relay 2"
    output: out_relay_2
  - id: relay_3
    platform: output
    name: "Relay 1"
    output: out_relay_3
  - id: relay_4
    platform: output
    name: "Relay 4 "
    output: out_relay_4

light:
  - platform: binary
    id: grow_light_1
    name: "Grow Light 1"
    output: out_relay_1

fan:
  - platform: binary
    id: exhaust_fan_1
    name: "Exhaust Fan"
    output: out_relay_2
  - platform: binary
    id: circulation_fan_1
    name: "Circulation Fan"
    output: out_relay_3


