esphome:
  name: back-entry-switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

text_sensor:
  - platform: version
    name: Sonoff T1 R2 Version

sensor:
  - platform: uptime
    name: Sonoff T1 R2 Uptime
    update_interval: 60s

binary_sensor:
  - name: "Sonoff Touchpad 1"
    platform: gpio
    pin:
      number: "GPIO0"
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: "GPIO9"
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay_2
    name: "Sonoff Touchpad 2"
  - platform: gpio
    pin:
      number: "GPIO10"
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Touchpad 3"
    on_press:
      - switch.toggle: relay_3
    
  - platform: status
    name: "Sonoff Status"

switch:
  - platform: gpio
    name: "Sonoff Relay 1"
    id: relay_1
    pin: GPIO12
  - platform: gpio
    name: "Sonoff Relay 2"
    id: relay_2
    pin: GPIO5
  - platform: gpio
    name: "Sonoff Relay 3"
    id: relay_3
    pin: GPIO4

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff Blue LED"
    output: blue_led