---
substitutions:
  devicename: growlight
  friendly_name: Grow Light

esphome:
  name: ${devicename}

esp8266:
  board: esp12e

<<: !include common.yaml

# Use the blue LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO2
    inverted: True

# x2 relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO5
    name: Relay1
    id: relay1
  - platform: gpio
    pin: GPIO4
    name: Relay2
    id: relay2
