# Sonoff 1 relay
substitutions:
  devicename: office-lamp-1
  friendly_name: Office Lamp 1

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.4.20.134

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$friendly_name Fallback Hotspot"
    password: "ZAEnApJTdSiy"

captive_portal:
logger:
api:
ota:

sensor:
  - platform: wifi_signal
    name: $friendly_name Wifi Signal
    update_interval: 60s

  - platform: uptime
    name: $friendly_name uptime

output:
  - id: out_relay
    platform: gpio
    pin:
      number: GPIO12

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$friendly_name Button"
    on_press:
      - light.toggle: light_1

light:
  - platform: binary
    id: light_1
    name: "$friendly_name Light"
    output: out_relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Detroit
    on_time:
      - seconds: 0
        minutes: 30
        hours: 7
        then:
          - light.turn_on: light_1
      - seconds: 0
        minutes: 00
        hours: 23
        then:
          - light.turn_off: light_1